apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nlp-
spec:
  arguments:
    parameters:
    - name: csv-url
      value: https://raw.githubusercontent.com/axsauze/reddit-classification-exploration/master/data/reddit_train.csv
    - name: csv-encoding
      value: ISO-8859-1
    - name: features-column
      value: BODY
    - name: labels-column
      value: REMOVED
    - name: raw-text-path
      value: /mnt/text.data
    - name: labels-path
      value: /mnt/labels.data
    - name: clean-text-path
      value: /mnt/clean.data
    - name: spacy-tokens-path
      value: /mnt/tokens.data
    - name: tfidf-vectors-path
      value: /mnt/tfidf.data
    - name: lr-prediction-path
      value: /mnt/prediction.data
    - name: tfidf-model-path
      value: /mnt/tfidf.model
    - name: lr-model-path
      value: /mnt/lr.model
    - name: lr-c-param
      value: '0.1'
    - name: tfidf-max-features
      value: '10000'
    - name: tfidf-ngram-range
      value: '3'
    - name: batch-size
      value: '100'
    - name: github-branch
      value: master
  entrypoint: nlp
  serviceAccountName: pipeline-runner
  templates:
  - dag:
      tasks:
      - name: patchpvcfinalizer
        template: patchpvcfinalizer
    name: nlp
  - container:
      command:
      - 'for j in $(kubectl get pvc -o name -l app=nlp,branch=master --field-selector
        metadata.name!=persistentvolumeclaim/nlp--b6f6013-vpimaph-my-pvc -n kubeflow);
        do kubectl patch $j -p ''{"metadata":{"finalizers": []}}'' -n kubeflow --type=merge;
        done'
      image: bitnami/kubectl
    name: patchpvcfinalizer
    outputs:
      artifacts:
      - name: mlpipeline-ui-metadata
        optional: true
        path: /mlpipeline-ui-metadata.json
      - name: mlpipeline-metrics
        optional: true
        path: /mlpipeline-metrics.json
