apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{workflow.name}}-my-pvc'
  namespace: kubeflow
  labels:
    branch: '{{workflow.parameters.github-branch}}'
    app: nlp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default