name: Test Kubectl

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
    - run: 'echo "$KUBE_CONFIG" > ./.kube_config'
      shell: bash
      env:
        KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
    - name: Step Three - Submit Argo Workflow from the examples/ folder in this repo
      id: argo
      uses: maximmold/actions-argo@master
      with:
        argo_url: "localhost:8083"
        workflow_yaml_path: "kubeflow/train_pipeline/pipeline.yaml"
        parameter_file_path: "argo/nlp-params.yaml"
        namespace: "kubeflow"
      env:
        KUBECONFIG: './.kube_config'