name: Test Kubectl

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
#    - uses: danielr1996/kubectl-action@1.0.0
#      name: Test
#      with:
#        kubeconfig: ${{ secrets.KUBE_CONFIG }}
#        args: apply -f argo/nlp-workflow.yaml
    - run: 'echo "$KUBE_CONFIG" > ./.kube_config'
      shell: bash
      env:
        KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
    - name: Step Three - Submit Argo Workflow from the examples/ folder in this repo
      id: argo
      uses: maximmold/actions-argo@master
      with:
        argo_url: "localhost:8082"
        workflow_yaml_path: "argo/nlp-workflow.yaml"
        parameter_file_path: "argo/nlp-params.yaml"
        namespace: "kubeflow"
        github_branch: "{{ github.ref }}"
      env:
        KUBECONFIG: './.kube_config'