name: Test Kubectl

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#    - name: Checkout code
#      uses: actions/checkout@master
#    - name: Setup python
#      uses: actions/setup-python@v1
#      with:
#        python-version: '3.x'
#        architecture: 'x64'
#    - name: Compile
#      run: |
#        pip3 install -r kubeflow/requirements-dev.txt --upgrade
#        cd kubeflow/train_pipeline
#        python3 nlp_pipeline.py
#    - name: Check
#      run: |
#        ls -lsa
#        tar -xvzf kubeflow/train_pipeline/nlp_pipeline.py.tar.gz
#        cat pipeline.yaml
    - run: echo "##[set-output name=random_string;]$(echo blah)"
      id: random_step
    - uses: danielr1996/kubectl-action@1.0.0
      name: Copy
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}
        args: -n kubeflow cp kubeflow/train_pipeline/nlp_pipeline.py.tar.gz `kubectl get po --no-headers -o custom-columns=":metadata.name" -l app=kfplctl -n kubeflow`:${{ steps.random_step.outputs.random_string }}.tar.gz
