name: Test Kubectl

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Compile
      run: |
        pip3 install -r kubeflow/requirements-dev.txt --upgrade
        cd kubeflow/train_pipeline
        python3 nlp_pipeline.py
    - name: Check
      run: |
        ls -lsa
        tar -xvzf kubeflow/train_pipeline/nlp_pipeline.py.tar.gz
        cat pipeline.yaml
    - run: 'mkdir ~/.kube; echo "$KUBE_CONFIG" > ~/.kube/config'
      shell: bash
      env:
        KUBE_CONFIG: ${{secrets.KUBE_CONFIG}}
    - name: Download kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x kubectl
    - name: Copy upload and start pipeline run
      run: |
        GITHUB_BRANCH=`[[ ! -z "$GITHUB_HEAD_REF" ]] && echo $GITHUB_HEAD_REF || echo  ${GITHUB_REF#refs/heads/}`
        echo filename nlp-$GITHUB_BRANCH.tar.gz
        SHA=${GITHUB_SHA}
        POD_NAME=$(./kubectl get po --no-headers -o custom-columns=":metadata.name" -l app=kfplctl -n kubeflow)
        echo [{\"name\": \"github-branch\",\"value\": \"${GITHUB_BRANCH}\"}] > nlp-params-${GITHUB_BRANCH}.json

        ./kubectl -n kubeflow cp kubeflow/train_pipeline/nlp_pipeline.py.tar.gz ${POD_NAME}:nlp-$GITHUB_BRANCH.tar.gz
        ./kubectl -n kubeflow cp nlp-params-${GITHUB_BRANCH}.json ${POD_NAME}:nlp-params-${GITHUB_BRANCH}.json

        ./kubectl -n kubeflow exec -i ${POD_NAME} -- kfplctl upload nlp-${GITHUB_BRANCH}-pipeline-${SHA} --pipeline nlp-${GITHUB_BRANCH}.tar.gz > plid.txt
        plid=$(cat plid.txt)
        echo "Pipeline ID:"
        echo $plid
        # use or create experiment
        echo "Check if experiment is already in place"
        eid="$(./kubectl -n kubeflow exec -i ${POD_NAME} --  kfplctl get experiment --name nlp-${GITHUB_BRANCH}-train-exp)"
        if [ -z "$eid" ]
        then
          echo "Creating new experiment"
          eid="$(./kubectl -n kubeflow exec -i ${POD_NAME} --  kfplctl create experiment nlp-${GITHUB_BRANCH}-train-exp)"
          echo "Experiment ID:"
          echo $eid
        else
          echo existing experiment $eid
        fi
        # create new run
        echo "Creating new run"
        rid="$(./kubectl -n kubeflow exec -i ${POD_NAME} -- kfplctl create run nlp-${GITHUB_BRANCH}-train-exp-${SHA} --parameters nlp-params-${GITHUB_BRANCH}.json --pipeline-id ${plid} --experiment-id ${eid})"
        echo run id ${rid}
        ./kubectl -n kubeflow exec -it ${POD_NAME} -- kfplctl get run $rid status
